# Generated by Django 4.2.5 on 2023-10-03 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskList_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profileimg',
            table='Profile_Picture',
        ),
    ]
